'use client'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from '@/SessionProvider'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer/Footer'
import { AppProvider } from '@/lib/context'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <AppProvider>
          <Navbar />
          {children}
          <Footer />
          </AppProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
